### ISSUE TITLE
Add Responsiveness to Homepage

### ISSUE THREAD

**Issue by arjxn-py** [arjxn-py/Curio#13]

**Comment by CodeTorso** [comment]
Give me 1 day.

**Comment by CodeTorso** [comment]
Sorry working on some other projects. Also the project seems dead

**Comment by arjxn-py** [comment]
> Sorry working on some other projects. Also the project seems dead

No worries, project is still active 🙂

**Comment by CodeTorso** [comment]
No commits since Ian I see

**Comment by arjxn-py** [comment]
> No commits since Ian I see

Yes, had to revert some of them since they were redundant. You can checkout the app [here](https://curiocic.netlify.app/)
Nevertheless happy to help with setting-up and onboarding whenever.

**Comment by CodeTorso** [comment]
Best of Luck then.

**Comment by SeaBebop** [comment]
Forked this project and I am attempting this issue. Got a couple of questions before I continue.

1. Do you want to continue using the unit px for majority of the project?
px is an fixed unit and further usage would require a lot of media queries to ensure responsiveness to both big screens and smaller screens.
The unit is causing overflows that would be resolved with other units like vw,vh. 
![ezgif-2-22466805c4](https://github.com/arjxn-py/Curio/assets/54507045/803f3575-d86a-4acb-a4b6-2308886d9f37)

2. How much would you like to be changed? 
With this version I only see the home page and the top menu would like a hamburger menu for smaller screens.
Currently I have changed somethings that are good for mobile and will continue with your reply.

**Comment by CodeTorso** [comment]
I am not the project maintainer. But you are right. Shifting to relative units is the best option. Try hamburger menu at the top of section. I believe you should also rem or em for font-size.

**Comment by SeaBebop** [comment]
Alright setting up the hamburger menu and changing units for now
